/*
 * Auto-generated LIN signal header
 * Created by your tool
 */

#ifndef LDF_TYPEDEFS_H
#define LDF_TYPEDEFS_H

#define LDF_VERSION "EQ7_KMatrix.ldf"

/* Definitions for Signal Length */
#define BCM_RGB_COLOR_U_01_LENGTH 7
#define BCM_RGB_COLOR_U_02_LENGTH 7
#define BCM_RGB_COLOR_U_03_LENGTH 7
#define BCM_RGB_COLOR_U_04_LENGTH 7
#define BCM_RGB_COLOR_U_05_LENGTH 7
#define BCM_RGB_COLOR_U_06_LENGTH 7
#define BCM_RGB_COLOR_U_07_LENGTH 7
#define BCM_RGB_COLOR_U_08_LENGTH 7
#define BCM_RGB_COLOR_U_09_LENGTH 7
#define BCM_RGB_COLOR_U_10_LENGTH 7
#define BCM_RGB_COLOR_U_11_LENGTH 7
#define BCM_RGB_COLOR_U_12_LENGTH 7
#define BCM_RGB_COLOR_U_13_LENGTH 7
#define BCM_RGB_COLOR_U_14_LENGTH 7
#define BCM_RGB_COLOR_V_01_LENGTH 7
#define BCM_RGB_COLOR_V_02_LENGTH 7
#define BCM_RGB_COLOR_V_03_LENGTH 7
#define BCM_RGB_COLOR_V_04_LENGTH 7
#define BCM_RGB_COLOR_V_05_LENGTH 7
#define BCM_RGB_COLOR_V_06_LENGTH 7
#define BCM_RGB_COLOR_V_07_LENGTH 7
#define BCM_RGB_COLOR_V_08_LENGTH 7
#define BCM_RGB_COLOR_V_09_LENGTH 7
#define BCM_RGB_COLOR_V_10_LENGTH 7
#define BCM_RGB_COLOR_V_11_LENGTH 7
#define BCM_RGB_COLOR_V_12_LENGTH 7
#define BCM_RGB_COLOR_V_13_LENGTH 7
#define BCM_RGB_COLOR_V_14_LENGTH 7
#define BCM_RGB_DIMMRAMPE_01_LENGTH 6
#define BCM_RGB_DIMMRAMPE_02_LENGTH 6
#define BCM_RGB_DIMMRAMPE_03_LENGTH 6
#define BCM_RGB_DIMMRAMPE_04_LENGTH 6
#define BCM_RGB_DIMMRAMPE_05_LENGTH 6
#define BCM_RGB_DIMMRAMPE_06_LENGTH 6
#define BCM_RGB_DIMMRAMPE_07_LENGTH 6
#define BCM_RGB_DIMMRAMPE_08_LENGTH 6
#define BCM_RGB_DIMMRAMPE_09_LENGTH 6
#define BCM_RGB_DIMMRAMPE_10_LENGTH 6
#define BCM_RGB_DIMMRAMPE_11_LENGTH 6
#define BCM_RGB_DIMMRAMPE_12_LENGTH 6
#define BCM_RGB_DIMMRAMPE_13_LENGTH 6
#define BCM_RGB_DIMMRAMPE_14_LENGTH 6
#define BCM_RGB_GLOBALSYNC_LENGTH 1
#define BCM_RGB_GLOBALSYNC_01_LENGTH 1
#define BCM_RGB_GLOBALSYNC_03_LENGTH 1
#define BCM_RGB_GLOBALSYNC_05_LENGTH 1
#define BCM_RGB_GLOBALSYNC_07_LENGTH 1
#define BCM_RGB_GLOBALSYNC_09_LENGTH 1
#define BCM_RGB_GLOBALSYNC_11_LENGTH 1
#define BCM_RGB_GLOBALSYNC_13_LENGTH 1
#define BCM_RGB_INTENSITAET_01_LENGTH 7
#define BCM_RGB_INTENSITAET_02_LENGTH 7
#define BCM_RGB_INTENSITAET_03_LENGTH 7
#define BCM_RGB_INTENSITAET_04_LENGTH 7
#define BCM_RGB_INTENSITAET_05_LENGTH 7
#define BCM_RGB_INTENSITAET_06_LENGTH 7
#define BCM_RGB_INTENSITAET_07_LENGTH 7
#define BCM_RGB_INTENSITAET_08_LENGTH 7
#define BCM_RGB_INTENSITAET_09_LENGTH 7
#define BCM_RGB_INTENSITAET_10_LENGTH 7
#define BCM_RGB_INTENSITAET_11_LENGTH 7
#define BCM_RGB_INTENSITAET_12_LENGTH 7
#define BCM_RGB_INTENSITAET_13_LENGTH 7
#define BCM_RGB_INTENSITAET_14_LENGTH 7
#define BCM_RGB_SONDERFUNKTION_01_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_02_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_03_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_04_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_05_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_06_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_07_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_08_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_09_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_10_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_11_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_12_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_13_LENGTH 4
#define BCM_RGB_SONDERFUNKTION_14_LENGTH 4
#define RGB_SLAVE_01D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_01D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_01D_INTERROR_LENGTH 2
#define RGB_SLAVE_01D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_01D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_01D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_01D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_01D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_01D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_02D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_02D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_02D_INTERROR_LENGTH 2
#define RGB_SLAVE_02D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_02D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_02D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_02D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_02D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_02D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_03D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_03D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_03D_INTERROR_LENGTH 2
#define RGB_SLAVE_03D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_03D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_03D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_03D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_03D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_03D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_04D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_04D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_04D_INTERROR_LENGTH 2
#define RGB_SLAVE_04D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_04D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_04D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_04D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_04D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_04D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_05D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_05D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_05D_INTERROR_LENGTH 2
#define RGB_SLAVE_05D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_05D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_05D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_05D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_05D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_05D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_06D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_06D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_06D_INTERROR_LENGTH 2
#define RGB_SLAVE_06D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_06D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_06D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_06D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_06D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_06D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_07D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_07D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_07D_INTERROR_LENGTH 2
#define RGB_SLAVE_07D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_07D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_07D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_07D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_07D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_07D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_08D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_08D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_08D_INTERROR_LENGTH 2
#define RGB_SLAVE_08D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_08D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_08D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_08D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_08D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_08D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_09D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_09D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_09D_INTERROR_LENGTH 2
#define RGB_SLAVE_09D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_09D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_09D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_09D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_09D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_09D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_10D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_10D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_10D_INTERROR_LENGTH 2
#define RGB_SLAVE_10D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_10D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_10D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_10D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_10D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_10D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_11D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_11D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_11D_INTERROR_LENGTH 2
#define RGB_SLAVE_11D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_11D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_11D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_11D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_11D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_11D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_12D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_12D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_12D_INTERROR_LENGTH 2
#define RGB_SLAVE_12D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_12D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_12D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_12D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_12D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_12D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_13D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_13D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_13D_INTERROR_LENGTH 2
#define RGB_SLAVE_13D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_13D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_13D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_13D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_13D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_13D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_14D_HELLIGKEITSFAKTOR_LENGTH 7
#define RGB_SLAVE_14D_HW_VERSION_LENGTH 8
#define RGB_SLAVE_14D_INTERROR_LENGTH 2
#define RGB_SLAVE_14D_RESPONSEERROR_LENGTH 1
#define RGB_SLAVE_14D_STOREDNAD_LENGTH 8
#define RGB_SLAVE_14D_SW_VERSION_LENGTH 8
#define RGB_SLAVE_14D_TEMPSTATE_LENGTH 3
#define RGB_SLAVE_14D_WEISSPUNKT_U_LENGTH 8
#define RGB_SLAVE_14D_WEISSPUNKT_V_LENGTH 8
#define RGB_SLAVE_16D_RESPONSEERROR_LENGTH 1
#define SWRITE_CRC_01_LENGTH 8
#define SWRITE_CRC_02_LENGTH 8
#define SWRITE_CRC_03_LENGTH 8
#define SWRITE_CRC_04_LENGTH 8
#define SWRITE_CRC_05_LENGTH 8
#define SWRITE_CRC_06_LENGTH 8
#define SWRITE_CRC_07_LENGTH 8
#define SWRITE_CRC_08_LENGTH 8
#define SWRITE_CRC_09_LENGTH 8
#define SWRITE_CRC_10_LENGTH 8
#define SWRITE_CRC_11_LENGTH 8
#define SWRITE_CRC_12_LENGTH 8
#define SWRITE_CRC_13_LENGTH 8
#define SWRITE_CRC_14_LENGTH 8
#define SWRITE_DATA_B1_01_LENGTH 8
#define SWRITE_DATA_B1_02_LENGTH 8
#define SWRITE_DATA_B1_03_LENGTH 8
#define SWRITE_DATA_B1_04_LENGTH 8
#define SWRITE_DATA_B1_05_LENGTH 8
#define SWRITE_DATA_B1_06_LENGTH 8
#define SWRITE_DATA_B1_07_LENGTH 8
#define SWRITE_DATA_B1_08_LENGTH 8
#define SWRITE_DATA_B1_09_LENGTH 8
#define SWRITE_DATA_B1_10_LENGTH 8
#define SWRITE_DATA_B1_11_LENGTH 8
#define SWRITE_DATA_B1_12_LENGTH 8
#define SWRITE_DATA_B1_13_LENGTH 8
#define SWRITE_DATA_B1_14_LENGTH 8
#define SWRITE_DATA_B2_01_LENGTH 8
#define SWRITE_DATA_B2_02_LENGTH 8
#define SWRITE_DATA_B2_03_LENGTH 8
#define SWRITE_DATA_B2_04_LENGTH 8
#define SWRITE_DATA_B2_05_LENGTH 8
#define SWRITE_DATA_B2_06_LENGTH 8
#define SWRITE_DATA_B2_07_LENGTH 8
#define SWRITE_DATA_B2_08_LENGTH 8
#define SWRITE_DATA_B2_09_LENGTH 8
#define SWRITE_DATA_B2_10_LENGTH 8
#define SWRITE_DATA_B2_11_LENGTH 8
#define SWRITE_DATA_B2_12_LENGTH 8
#define SWRITE_DATA_B2_13_LENGTH 8
#define SWRITE_DATA_B2_14_LENGTH 8
#define SWRITE_DATA_B3_01_LENGTH 8
#define SWRITE_DATA_B3_02_LENGTH 8
#define SWRITE_DATA_B3_03_LENGTH 8
#define SWRITE_DATA_B3_04_LENGTH 8
#define SWRITE_DATA_B3_05_LENGTH 8
#define SWRITE_DATA_B3_06_LENGTH 8
#define SWRITE_DATA_B3_07_LENGTH 8
#define SWRITE_DATA_B3_08_LENGTH 8
#define SWRITE_DATA_B3_09_LENGTH 8
#define SWRITE_DATA_B3_10_LENGTH 8
#define SWRITE_DATA_B3_11_LENGTH 8
#define SWRITE_DATA_B3_12_LENGTH 8
#define SWRITE_DATA_B3_13_LENGTH 8
#define SWRITE_DATA_B3_14_LENGTH 8
#define SWRITE_DATA_B4_01_LENGTH 8
#define SWRITE_DATA_B4_02_LENGTH 8
#define SWRITE_DATA_B4_03_LENGTH 8
#define SWRITE_DATA_B4_04_LENGTH 8
#define SWRITE_DATA_B4_05_LENGTH 8
#define SWRITE_DATA_B4_06_LENGTH 8
#define SWRITE_DATA_B4_07_LENGTH 8
#define SWRITE_DATA_B4_08_LENGTH 8
#define SWRITE_DATA_B4_09_LENGTH 8
#define SWRITE_DATA_B4_10_LENGTH 8
#define SWRITE_DATA_B4_11_LENGTH 8
#define SWRITE_DATA_B4_12_LENGTH 8
#define SWRITE_DATA_B4_13_LENGTH 8
#define SWRITE_DATA_B4_14_LENGTH 8
#define SWRITE_DATA_B5_01_LENGTH 8
#define SWRITE_DATA_B5_02_LENGTH 8
#define SWRITE_DATA_B5_03_LENGTH 8
#define SWRITE_DATA_B5_04_LENGTH 8
#define SWRITE_DATA_B5_05_LENGTH 8
#define SWRITE_DATA_B5_06_LENGTH 8
#define SWRITE_DATA_B5_07_LENGTH 8
#define SWRITE_DATA_B5_08_LENGTH 8
#define SWRITE_DATA_B5_09_LENGTH 8
#define SWRITE_DATA_B5_10_LENGTH 8
#define SWRITE_DATA_B5_11_LENGTH 8
#define SWRITE_DATA_B5_12_LENGTH 8
#define SWRITE_DATA_B5_13_LENGTH 8
#define SWRITE_DATA_B5_14_LENGTH 8
#define SWRITE_DUMMY_01_LENGTH 5
#define SWRITE_DUMMY_02_LENGTH 5
#define SWRITE_DUMMY_03_LENGTH 5
#define SWRITE_DUMMY_04_LENGTH 5
#define SWRITE_DUMMY_05_LENGTH 5
#define SWRITE_DUMMY_06_LENGTH 5
#define SWRITE_DUMMY_07_LENGTH 5
#define SWRITE_DUMMY_08_LENGTH 5
#define SWRITE_DUMMY_09_LENGTH 5
#define SWRITE_DUMMY_10_LENGTH 5
#define SWRITE_DUMMY_11_LENGTH 5
#define SWRITE_DUMMY_12_LENGTH 5
#define SWRITE_DUMMY_13_LENGTH 5
#define SWRITE_DUMMY_14_LENGTH 5
#define SWRITE_LEN_01_LENGTH 3
#define SWRITE_LEN_02_LENGTH 3
#define SWRITE_LEN_03_LENGTH 3
#define SWRITE_LEN_04_LENGTH 3
#define SWRITE_LEN_05_LENGTH 3
#define SWRITE_LEN_06_LENGTH 3
#define SWRITE_LEN_07_LENGTH 3
#define SWRITE_LEN_08_LENGTH 3
#define SWRITE_LEN_09_LENGTH 3
#define SWRITE_LEN_10_LENGTH 3
#define SWRITE_LEN_11_LENGTH 3
#define SWRITE_LEN_12_LENGTH 3
#define SWRITE_LEN_13_LENGTH 3
#define SWRITE_LEN_14_LENGTH 3
#define SWRITE_MEMADDRESS_01_LENGTH 8
#define SWRITE_MEMADDRESS_02_LENGTH 8
#define SWRITE_MEMADDRESS_03_LENGTH 8
#define SWRITE_MEMADDRESS_04_LENGTH 8
#define SWRITE_MEMADDRESS_05_LENGTH 8
#define SWRITE_MEMADDRESS_06_LENGTH 8
#define SWRITE_MEMADDRESS_07_LENGTH 8
#define SWRITE_MEMADDRESS_08_LENGTH 8
#define SWRITE_MEMADDRESS_09_LENGTH 8
#define SWRITE_MEMADDRESS_10_LENGTH 8
#define SWRITE_MEMADDRESS_11_LENGTH 8
#define SWRITE_MEMADDRESS_12_LENGTH 8
#define SWRITE_MEMADDRESS_13_LENGTH 8
#define SWRITE_MEMADDRESS_14_LENGTH 8


/* Definitions for Signal Offset */
#define BCM_RGB_COLOR_U_01_OFFSET 0
#define BCM_RGB_COLOR_V_01_OFFSET 7
#define BCM_RGB_DIMMRAMPE_01_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_01_OFFSET 20
#define BCM_RGB_INTENSITAET_01_OFFSET 24
#define BCM_RGB_COLOR_U_02_OFFSET 32
#define BCM_RGB_COLOR_V_02_OFFSET 39
#define BCM_RGB_DIMMRAMPE_02_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_02_OFFSET 52
#define BCM_RGB_INTENSITAET_02_OFFSET 56
#define BCM_RGB_GLOBALSYNC_01_OFFSET 63

#define BCM_RGB_COLOR_U_03_OFFSET 0
#define BCM_RGB_COLOR_V_03_OFFSET 7
#define BCM_RGB_DIMMRAMPE_03_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_03_OFFSET 20
#define BCM_RGB_INTENSITAET_03_OFFSET 24
#define BCM_RGB_COLOR_U_04_OFFSET 32
#define BCM_RGB_COLOR_V_04_OFFSET 39
#define BCM_RGB_DIMMRAMPE_04_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_04_OFFSET 52
#define BCM_RGB_INTENSITAET_04_OFFSET 56
#define BCM_RGB_GLOBALSYNC_03_OFFSET 63

#define BCM_RGB_COLOR_U_05_OFFSET 0
#define BCM_RGB_COLOR_V_05_OFFSET 7
#define BCM_RGB_DIMMRAMPE_05_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_05_OFFSET 20
#define BCM_RGB_INTENSITAET_05_OFFSET 24
#define BCM_RGB_COLOR_U_06_OFFSET 32
#define BCM_RGB_COLOR_V_06_OFFSET 39
#define BCM_RGB_DIMMRAMPE_06_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_06_OFFSET 52
#define BCM_RGB_INTENSITAET_06_OFFSET 56
#define BCM_RGB_GLOBALSYNC_05_OFFSET 63

#define BCM_RGB_COLOR_U_07_OFFSET 0
#define BCM_RGB_COLOR_V_07_OFFSET 7
#define BCM_RGB_DIMMRAMPE_07_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_07_OFFSET 20
#define BCM_RGB_INTENSITAET_07_OFFSET 24
#define BCM_RGB_COLOR_U_08_OFFSET 32
#define BCM_RGB_COLOR_V_08_OFFSET 39
#define BCM_RGB_DIMMRAMPE_08_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_08_OFFSET 52
#define BCM_RGB_INTENSITAET_08_OFFSET 56
#define BCM_RGB_GLOBALSYNC_07_OFFSET 63

#define BCM_RGB_COLOR_U_09_OFFSET 0
#define BCM_RGB_COLOR_V_09_OFFSET 7
#define BCM_RGB_DIMMRAMPE_09_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_09_OFFSET 20
#define BCM_RGB_INTENSITAET_09_OFFSET 24
#define BCM_RGB_COLOR_U_10_OFFSET 32
#define BCM_RGB_COLOR_V_10_OFFSET 39
#define BCM_RGB_DIMMRAMPE_10_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_10_OFFSET 52
#define BCM_RGB_INTENSITAET_10_OFFSET 56
#define BCM_RGB_GLOBALSYNC_09_OFFSET 63

#define BCM_RGB_COLOR_U_11_OFFSET 0
#define BCM_RGB_COLOR_V_11_OFFSET 7
#define BCM_RGB_DIMMRAMPE_11_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_11_OFFSET 20
#define BCM_RGB_INTENSITAET_11_OFFSET 24
#define BCM_RGB_COLOR_U_12_OFFSET 32
#define BCM_RGB_COLOR_V_12_OFFSET 39
#define BCM_RGB_DIMMRAMPE_12_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_12_OFFSET 52
#define BCM_RGB_INTENSITAET_12_OFFSET 56
#define BCM_RGB_GLOBALSYNC_11_OFFSET 63

#define BCM_RGB_COLOR_U_13_OFFSET 0
#define BCM_RGB_COLOR_V_13_OFFSET 7
#define BCM_RGB_DIMMRAMPE_13_OFFSET 14
#define BCM_RGB_SONDERFUNKTION_13_OFFSET 20
#define BCM_RGB_INTENSITAET_13_OFFSET 24
#define BCM_RGB_COLOR_U_14_OFFSET 32
#define BCM_RGB_COLOR_V_14_OFFSET 39
#define BCM_RGB_DIMMRAMPE_14_OFFSET 46
#define BCM_RGB_SONDERFUNKTION_14_OFFSET 52
#define BCM_RGB_INTENSITAET_14_OFFSET 56
#define BCM_RGB_GLOBALSYNC_13_OFFSET 63

#define BCM_RGB_GLOBALSYNC_OFFSET 0

#define SWRITE_DUMMY_01_OFFSET 0
#define SWRITE_LEN_01_OFFSET 5
#define SWRITE_MEMADDRESS_01_OFFSET 8
#define SWRITE_DATA_B1_01_OFFSET 16
#define SWRITE_DATA_B2_01_OFFSET 24
#define SWRITE_DATA_B3_01_OFFSET 32
#define SWRITE_DATA_B4_01_OFFSET 40
#define SWRITE_DATA_B5_01_OFFSET 48
#define SWRITE_CRC_01_OFFSET 56

#define SWRITE_DUMMY_02_OFFSET 0
#define SWRITE_LEN_02_OFFSET 5
#define SWRITE_MEMADDRESS_02_OFFSET 8
#define SWRITE_DATA_B1_02_OFFSET 16
#define SWRITE_DATA_B2_02_OFFSET 24
#define SWRITE_DATA_B3_02_OFFSET 32
#define SWRITE_DATA_B4_02_OFFSET 40
#define SWRITE_DATA_B5_02_OFFSET 48
#define SWRITE_CRC_02_OFFSET 56

#define SWRITE_DUMMY_03_OFFSET 0
#define SWRITE_LEN_03_OFFSET 5
#define SWRITE_MEMADDRESS_03_OFFSET 8
#define SWRITE_DATA_B1_03_OFFSET 16
#define SWRITE_DATA_B2_03_OFFSET 24
#define SWRITE_DATA_B3_03_OFFSET 32
#define SWRITE_DATA_B4_03_OFFSET 40
#define SWRITE_DATA_B5_03_OFFSET 48
#define SWRITE_CRC_03_OFFSET 56

#define SWRITE_DUMMY_04_OFFSET 0
#define SWRITE_LEN_04_OFFSET 5
#define SWRITE_MEMADDRESS_04_OFFSET 8
#define SWRITE_DATA_B1_04_OFFSET 16
#define SWRITE_DATA_B2_04_OFFSET 24
#define SWRITE_DATA_B3_04_OFFSET 32
#define SWRITE_DATA_B4_04_OFFSET 40
#define SWRITE_DATA_B5_04_OFFSET 48
#define SWRITE_CRC_04_OFFSET 56

#define SWRITE_DUMMY_05_OFFSET 0
#define SWRITE_LEN_05_OFFSET 5
#define SWRITE_MEMADDRESS_05_OFFSET 8
#define SWRITE_DATA_B1_05_OFFSET 16
#define SWRITE_DATA_B2_05_OFFSET 24
#define SWRITE_DATA_B3_05_OFFSET 32
#define SWRITE_DATA_B4_05_OFFSET 40
#define SWRITE_DATA_B5_05_OFFSET 48
#define SWRITE_CRC_05_OFFSET 56

#define SWRITE_DUMMY_06_OFFSET 0
#define SWRITE_LEN_06_OFFSET 5
#define SWRITE_MEMADDRESS_06_OFFSET 8
#define SWRITE_DATA_B1_06_OFFSET 16
#define SWRITE_DATA_B2_06_OFFSET 24
#define SWRITE_DATA_B3_06_OFFSET 32
#define SWRITE_DATA_B4_06_OFFSET 40
#define SWRITE_DATA_B5_06_OFFSET 48
#define SWRITE_CRC_06_OFFSET 56

#define SWRITE_DUMMY_07_OFFSET 0
#define SWRITE_LEN_07_OFFSET 5
#define SWRITE_MEMADDRESS_07_OFFSET 8
#define SWRITE_DATA_B1_07_OFFSET 16
#define SWRITE_DATA_B2_07_OFFSET 24
#define SWRITE_DATA_B3_07_OFFSET 32
#define SWRITE_DATA_B4_07_OFFSET 40
#define SWRITE_DATA_B5_07_OFFSET 48
#define SWRITE_CRC_07_OFFSET 56

#define SWRITE_DUMMY_08_OFFSET 0
#define SWRITE_LEN_08_OFFSET 5
#define SWRITE_MEMADDRESS_08_OFFSET 8
#define SWRITE_DATA_B1_08_OFFSET 16
#define SWRITE_DATA_B2_08_OFFSET 24
#define SWRITE_DATA_B3_08_OFFSET 32
#define SWRITE_DATA_B4_08_OFFSET 40
#define SWRITE_DATA_B5_08_OFFSET 48
#define SWRITE_CRC_08_OFFSET 56

#define SWRITE_DUMMY_09_OFFSET 0
#define SWRITE_LEN_09_OFFSET 5
#define SWRITE_MEMADDRESS_09_OFFSET 8
#define SWRITE_DATA_B1_09_OFFSET 16
#define SWRITE_DATA_B2_09_OFFSET 24
#define SWRITE_DATA_B3_09_OFFSET 32
#define SWRITE_DATA_B4_09_OFFSET 40
#define SWRITE_DATA_B5_09_OFFSET 48
#define SWRITE_CRC_09_OFFSET 56

#define SWRITE_DUMMY_10_OFFSET 0
#define SWRITE_LEN_10_OFFSET 5
#define SWRITE_MEMADDRESS_10_OFFSET 8
#define SWRITE_DATA_B1_10_OFFSET 16
#define SWRITE_DATA_B2_10_OFFSET 24
#define SWRITE_DATA_B3_10_OFFSET 32
#define SWRITE_DATA_B4_10_OFFSET 40
#define SWRITE_DATA_B5_10_OFFSET 48
#define SWRITE_CRC_10_OFFSET 56

#define SWRITE_DUMMY_11_OFFSET 0
#define SWRITE_LEN_11_OFFSET 5
#define SWRITE_MEMADDRESS_11_OFFSET 8
#define SWRITE_DATA_B1_11_OFFSET 16
#define SWRITE_DATA_B2_11_OFFSET 24
#define SWRITE_DATA_B3_11_OFFSET 32
#define SWRITE_DATA_B4_11_OFFSET 40
#define SWRITE_DATA_B5_11_OFFSET 48
#define SWRITE_CRC_11_OFFSET 56

#define SWRITE_DUMMY_12_OFFSET 0
#define SWRITE_LEN_12_OFFSET 5
#define SWRITE_MEMADDRESS_12_OFFSET 8
#define SWRITE_DATA_B1_12_OFFSET 16
#define SWRITE_DATA_B2_12_OFFSET 24
#define SWRITE_DATA_B3_12_OFFSET 32
#define SWRITE_DATA_B4_12_OFFSET 40
#define SWRITE_DATA_B5_12_OFFSET 48
#define SWRITE_CRC_12_OFFSET 56

#define SWRITE_DUMMY_13_OFFSET 0
#define SWRITE_LEN_13_OFFSET 5
#define SWRITE_MEMADDRESS_13_OFFSET 8
#define SWRITE_DATA_B1_13_OFFSET 16
#define SWRITE_DATA_B2_13_OFFSET 24
#define SWRITE_DATA_B3_13_OFFSET 32
#define SWRITE_DATA_B4_13_OFFSET 40
#define SWRITE_DATA_B5_13_OFFSET 48
#define SWRITE_CRC_13_OFFSET 56

#define SWRITE_DUMMY_14_OFFSET 0
#define SWRITE_LEN_14_OFFSET 5
#define SWRITE_MEMADDRESS_14_OFFSET 8
#define SWRITE_DATA_B1_14_OFFSET 16
#define SWRITE_DATA_B2_14_OFFSET 24
#define SWRITE_DATA_B3_14_OFFSET 32
#define SWRITE_DATA_B4_14_OFFSET 40
#define SWRITE_DATA_B5_14_OFFSET 48
#define SWRITE_CRC_14_OFFSET 56

#define RGB_SLAVE_01D_INTERROR_OFFSET 0
#define RGB_SLAVE_01D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_01D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_01D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_01D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_01D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_01D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_01D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_01D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_02D_INTERROR_OFFSET 0
#define RGB_SLAVE_02D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_02D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_02D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_02D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_02D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_02D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_02D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_02D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_03D_INTERROR_OFFSET 0
#define RGB_SLAVE_03D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_03D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_03D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_03D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_03D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_03D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_03D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_03D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_04D_INTERROR_OFFSET 0
#define RGB_SLAVE_04D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_04D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_04D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_04D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_04D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_04D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_04D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_04D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_05D_INTERROR_OFFSET 0
#define RGB_SLAVE_05D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_05D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_05D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_05D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_05D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_05D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_05D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_05D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_06D_INTERROR_OFFSET 0
#define RGB_SLAVE_06D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_06D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_06D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_06D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_06D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_06D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_06D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_06D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_07D_INTERROR_OFFSET 0
#define RGB_SLAVE_07D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_07D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_07D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_07D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_07D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_07D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_07D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_07D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_08D_INTERROR_OFFSET 0
#define RGB_SLAVE_08D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_08D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_08D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_08D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_08D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_08D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_08D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_08D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_09D_INTERROR_OFFSET 0
#define RGB_SLAVE_09D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_09D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_09D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_09D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_09D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_09D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_09D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_09D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_10D_INTERROR_OFFSET 0
#define RGB_SLAVE_10D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_10D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_10D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_10D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_10D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_10D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_10D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_10D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_11D_INTERROR_OFFSET 0
#define RGB_SLAVE_11D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_11D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_11D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_11D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_11D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_11D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_11D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_11D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_12D_INTERROR_OFFSET 0
#define RGB_SLAVE_12D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_12D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_12D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_12D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_12D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_12D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_12D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_12D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_13D_INTERROR_OFFSET 0
#define RGB_SLAVE_13D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_13D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_13D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_13D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_13D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_13D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_13D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_13D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_14D_INTERROR_OFFSET 0
#define RGB_SLAVE_14D_TEMPSTATE_OFFSET 4
#define RGB_SLAVE_14D_RESPONSEERROR_OFFSET 7
#define RGB_SLAVE_14D_HELLIGKEITSFAKTOR_OFFSET 8
#define RGB_SLAVE_14D_HW_VERSION_OFFSET 16
#define RGB_SLAVE_14D_SW_VERSION_OFFSET 24
#define RGB_SLAVE_14D_STOREDNAD_OFFSET 32
#define RGB_SLAVE_14D_WEISSPUNKT_U_OFFSET 40
#define RGB_SLAVE_14D_WEISSPUNKT_V_OFFSET 48

#define RGB_SLAVE_16D_RESPONSEERROR_OFFSET 7

#define ST1_FRAMESIZE 120
#define SWRITE_FRAMESIZE 14
#define SYNC_ALL_FRAMESIZE 1
#define DIAGREQUEST_FRAMESIZE 1
#define DIAGRESPONSE_FRAMESIZE 1

// LIN-Bus Nodes
typedef enum {
    HCP4_uC1_1,
    AM_RGB_Slave_01d,
    AM_RGB_Slave_02d,
    AM_RGB_Slave_03d,
    AM_RGB_Slave_04d,
    AM_RGB_Slave_05d,
    AM_RGB_Slave_06d,
    AM_RGB_Slave_07d,
    AM_RGB_Slave_08d,
    AM_RGB_Slave_09d,
    AM_RGB_Slave_10d,
    AM_RGB_Slave_11d,
    AM_RGB_Slave_12d,
    AM_RGB_Slave_13d,
    AM_RGB_Slave_14d,
    Virtual_AM_RGB_Slave_16d
} Nodes;

// LIN-Bus Signals
typedef enum {
    BCM_RGB_Color_u_01,
    BCM_RGB_Color_u_02,
    BCM_RGB_Color_u_03,
    BCM_RGB_Color_u_04,
    BCM_RGB_Color_u_05,
    BCM_RGB_Color_u_06,
    BCM_RGB_Color_u_07,
    BCM_RGB_Color_u_08,
    BCM_RGB_Color_u_09,
    BCM_RGB_Color_u_10,
    BCM_RGB_Color_u_11,
    BCM_RGB_Color_u_12,
    BCM_RGB_Color_u_13,
    BCM_RGB_Color_u_14,
    BCM_RGB_Color_v_01,
    BCM_RGB_Color_v_02,
    BCM_RGB_Color_v_03,
    BCM_RGB_Color_v_04,
    BCM_RGB_Color_v_05,
    BCM_RGB_Color_v_06,
    BCM_RGB_Color_v_07,
    BCM_RGB_Color_v_08,
    BCM_RGB_Color_v_09,
    BCM_RGB_Color_v_10,
    BCM_RGB_Color_v_11,
    BCM_RGB_Color_v_12,
    BCM_RGB_Color_v_13,
    BCM_RGB_Color_v_14,
    BCM_RGB_Dimmrampe_01,
    BCM_RGB_Dimmrampe_02,
    BCM_RGB_Dimmrampe_03,
    BCM_RGB_Dimmrampe_04,
    BCM_RGB_Dimmrampe_05,
    BCM_RGB_Dimmrampe_06,
    BCM_RGB_Dimmrampe_07,
    BCM_RGB_Dimmrampe_08,
    BCM_RGB_Dimmrampe_09,
    BCM_RGB_Dimmrampe_10,
    BCM_RGB_Dimmrampe_11,
    BCM_RGB_Dimmrampe_12,
    BCM_RGB_Dimmrampe_13,
    BCM_RGB_Dimmrampe_14,
    BCM_RGB_GlobalSync,
    BCM_RGB_GlobalSync_01,
    BCM_RGB_GlobalSync_03,
    BCM_RGB_GlobalSync_05,
    BCM_RGB_GlobalSync_07,
    BCM_RGB_GlobalSync_09,
    BCM_RGB_GlobalSync_11,
    BCM_RGB_GlobalSync_13,
    BCM_RGB_Intensitaet_01,
    BCM_RGB_Intensitaet_02,
    BCM_RGB_Intensitaet_03,
    BCM_RGB_Intensitaet_04,
    BCM_RGB_Intensitaet_05,
    BCM_RGB_Intensitaet_06,
    BCM_RGB_Intensitaet_07,
    BCM_RGB_Intensitaet_08,
    BCM_RGB_Intensitaet_09,
    BCM_RGB_Intensitaet_10,
    BCM_RGB_Intensitaet_11,
    BCM_RGB_Intensitaet_12,
    BCM_RGB_Intensitaet_13,
    BCM_RGB_Intensitaet_14,
    BCM_RGB_Sonderfunktion_01,
    BCM_RGB_Sonderfunktion_02,
    BCM_RGB_Sonderfunktion_03,
    BCM_RGB_Sonderfunktion_04,
    BCM_RGB_Sonderfunktion_05,
    BCM_RGB_Sonderfunktion_06,
    BCM_RGB_Sonderfunktion_07,
    BCM_RGB_Sonderfunktion_08,
    BCM_RGB_Sonderfunktion_09,
    BCM_RGB_Sonderfunktion_10,
    BCM_RGB_Sonderfunktion_11,
    BCM_RGB_Sonderfunktion_12,
    BCM_RGB_Sonderfunktion_13,
    BCM_RGB_Sonderfunktion_14,
    RGB_Slave_01d_HelligkeitsFaktor,
    RGB_Slave_01d_HW_Version,
    RGB_Slave_01d_IntError,
    RGB_Slave_01d_ResponseError,
    RGB_Slave_01d_StoredNAD,
    RGB_Slave_01d_SW_Version,
    RGB_Slave_01d_TempState,
    RGB_Slave_01d_Weisspunkt_u,
    RGB_Slave_01d_Weisspunkt_v,
    RGB_Slave_02d_HelligkeitsFaktor,
    RGB_Slave_02d_HW_Version,
    RGB_Slave_02d_IntError,
    RGB_Slave_02d_ResponseError,
    RGB_Slave_02d_StoredNAD,
    RGB_Slave_02d_SW_Version,
    RGB_Slave_02d_TempState,
    RGB_Slave_02d_Weisspunkt_u,
    RGB_Slave_02d_Weisspunkt_v,
    RGB_Slave_03d_HelligkeitsFaktor,
    RGB_Slave_03d_HW_Version,
    RGB_Slave_03d_IntError,
    RGB_Slave_03d_ResponseError,
    RGB_Slave_03d_StoredNAD,
    RGB_Slave_03d_SW_Version,
    RGB_Slave_03d_TempState,
    RGB_Slave_03d_Weisspunkt_u,
    RGB_Slave_03d_Weisspunkt_v,
    RGB_Slave_04d_HelligkeitsFaktor,
    RGB_Slave_04d_HW_Version,
    RGB_Slave_04d_IntError,
    RGB_Slave_04d_ResponseError,
    RGB_Slave_04d_StoredNAD,
    RGB_Slave_04d_SW_Version,
    RGB_Slave_04d_TempState,
    RGB_Slave_04d_Weisspunkt_u,
    RGB_Slave_04d_Weisspunkt_v,
    RGB_Slave_05d_HelligkeitsFaktor,
    RGB_Slave_05d_HW_Version,
    RGB_Slave_05d_IntError,
    RGB_Slave_05d_ResponseError,
    RGB_Slave_05d_StoredNAD,
    RGB_Slave_05d_SW_Version,
    RGB_Slave_05d_TempState,
    RGB_Slave_05d_Weisspunkt_u,
    RGB_Slave_05d_Weisspunkt_v,
    RGB_Slave_06d_HelligkeitsFaktor,
    RGB_Slave_06d_HW_Version,
    RGB_Slave_06d_IntError,
    RGB_Slave_06d_ResponseError,
    RGB_Slave_06d_StoredNAD,
    RGB_Slave_06d_SW_Version,
    RGB_Slave_06d_TempState,
    RGB_Slave_06d_Weisspunkt_u,
    RGB_Slave_06d_Weisspunkt_v,
    RGB_Slave_07d_HelligkeitsFaktor,
    RGB_Slave_07d_HW_Version,
    RGB_Slave_07d_IntError,
    RGB_Slave_07d_ResponseError,
    RGB_Slave_07d_StoredNAD,
    RGB_Slave_07d_SW_Version,
    RGB_Slave_07d_TempState,
    RGB_Slave_07d_Weisspunkt_u,
    RGB_Slave_07d_Weisspunkt_v,
    RGB_Slave_08d_HelligkeitsFaktor,
    RGB_Slave_08d_HW_Version,
    RGB_Slave_08d_IntError,
    RGB_Slave_08d_ResponseError,
    RGB_Slave_08d_StoredNAD,
    RGB_Slave_08d_SW_Version,
    RGB_Slave_08d_TempState,
    RGB_Slave_08d_Weisspunkt_u,
    RGB_Slave_08d_Weisspunkt_v,
    RGB_Slave_09d_HelligkeitsFaktor,
    RGB_Slave_09d_HW_Version,
    RGB_Slave_09d_IntError,
    RGB_Slave_09d_ResponseError,
    RGB_Slave_09d_StoredNAD,
    RGB_Slave_09d_SW_Version,
    RGB_Slave_09d_TempState,
    RGB_Slave_09d_Weisspunkt_u,
    RGB_Slave_09d_Weisspunkt_v,
    RGB_Slave_10d_HelligkeitsFaktor,
    RGB_Slave_10d_HW_Version,
    RGB_Slave_10d_IntError,
    RGB_Slave_10d_ResponseError,
    RGB_Slave_10d_StoredNAD,
    RGB_Slave_10d_SW_Version,
    RGB_Slave_10d_TempState,
    RGB_Slave_10d_Weisspunkt_u,
    RGB_Slave_10d_Weisspunkt_v,
    RGB_Slave_11d_HelligkeitsFaktor,
    RGB_Slave_11d_HW_Version,
    RGB_Slave_11d_IntError,
    RGB_Slave_11d_ResponseError,
    RGB_Slave_11d_StoredNAD,
    RGB_Slave_11d_SW_Version,
    RGB_Slave_11d_TempState,
    RGB_Slave_11d_Weisspunkt_u,
    RGB_Slave_11d_Weisspunkt_v,
    RGB_Slave_12d_HelligkeitsFaktor,
    RGB_Slave_12d_HW_Version,
    RGB_Slave_12d_IntError,
    RGB_Slave_12d_ResponseError,
    RGB_Slave_12d_StoredNAD,
    RGB_Slave_12d_SW_Version,
    RGB_Slave_12d_TempState,
    RGB_Slave_12d_Weisspunkt_u,
    RGB_Slave_12d_Weisspunkt_v,
    RGB_Slave_13d_HelligkeitsFaktor,
    RGB_Slave_13d_HW_Version,
    RGB_Slave_13d_IntError,
    RGB_Slave_13d_ResponseError,
    RGB_Slave_13d_StoredNAD,
    RGB_Slave_13d_SW_Version,
    RGB_Slave_13d_TempState,
    RGB_Slave_13d_Weisspunkt_u,
    RGB_Slave_13d_Weisspunkt_v,
    RGB_Slave_14d_HelligkeitsFaktor,
    RGB_Slave_14d_HW_Version,
    RGB_Slave_14d_IntError,
    RGB_Slave_14d_ResponseError,
    RGB_Slave_14d_StoredNAD,
    RGB_Slave_14d_SW_Version,
    RGB_Slave_14d_TempState,
    RGB_Slave_14d_Weisspunkt_u,
    RGB_Slave_14d_Weisspunkt_v,
    RGB_Slave_16d_ResponseError,
    SWrite_CRC_01,
    SWrite_CRC_02,
    SWrite_CRC_03,
    SWrite_CRC_04,
    SWrite_CRC_05,
    SWrite_CRC_06,
    SWrite_CRC_07,
    SWrite_CRC_08,
    SWrite_CRC_09,
    SWrite_CRC_10,
    SWrite_CRC_11,
    SWrite_CRC_12,
    SWrite_CRC_13,
    SWrite_CRC_14,
    SWrite_Data_B1_01,
    SWrite_Data_B1_02,
    SWrite_Data_B1_03,
    SWrite_Data_B1_04,
    SWrite_Data_B1_05,
    SWrite_Data_B1_06,
    SWrite_Data_B1_07,
    SWrite_Data_B1_08,
    SWrite_Data_B1_09,
    SWrite_Data_B1_10,
    SWrite_Data_B1_11,
    SWrite_Data_B1_12,
    SWrite_Data_B1_13,
    SWrite_Data_B1_14,
    SWrite_Data_B2_01,
    SWrite_Data_B2_02,
    SWrite_Data_B2_03,
    SWrite_Data_B2_04,
    SWrite_Data_B2_05,
    SWrite_Data_B2_06,
    SWrite_Data_B2_07,
    SWrite_Data_B2_08,
    SWrite_Data_B2_09,
    SWrite_Data_B2_10,
    SWrite_Data_B2_11,
    SWrite_Data_B2_12,
    SWrite_Data_B2_13,
    SWrite_Data_B2_14,
    SWrite_Data_B3_01,
    SWrite_Data_B3_02,
    SWrite_Data_B3_03,
    SWrite_Data_B3_04,
    SWrite_Data_B3_05,
    SWrite_Data_B3_06,
    SWrite_Data_B3_07,
    SWrite_Data_B3_08,
    SWrite_Data_B3_09,
    SWrite_Data_B3_10,
    SWrite_Data_B3_11,
    SWrite_Data_B3_12,
    SWrite_Data_B3_13,
    SWrite_Data_B3_14,
    SWrite_Data_B4_01,
    SWrite_Data_B4_02,
    SWrite_Data_B4_03,
    SWrite_Data_B4_04,
    SWrite_Data_B4_05,
    SWrite_Data_B4_06,
    SWrite_Data_B4_07,
    SWrite_Data_B4_08,
    SWrite_Data_B4_09,
    SWrite_Data_B4_10,
    SWrite_Data_B4_11,
    SWrite_Data_B4_12,
    SWrite_Data_B4_13,
    SWrite_Data_B4_14,
    SWrite_Data_B5_01,
    SWrite_Data_B5_02,
    SWrite_Data_B5_03,
    SWrite_Data_B5_04,
    SWrite_Data_B5_05,
    SWrite_Data_B5_06,
    SWrite_Data_B5_07,
    SWrite_Data_B5_08,
    SWrite_Data_B5_09,
    SWrite_Data_B5_10,
    SWrite_Data_B5_11,
    SWrite_Data_B5_12,
    SWrite_Data_B5_13,
    SWrite_Data_B5_14,
    SWrite_Dummy_01,
    SWrite_Dummy_02,
    SWrite_Dummy_03,
    SWrite_Dummy_04,
    SWrite_Dummy_05,
    SWrite_Dummy_06,
    SWrite_Dummy_07,
    SWrite_Dummy_08,
    SWrite_Dummy_09,
    SWrite_Dummy_10,
    SWrite_Dummy_11,
    SWrite_Dummy_12,
    SWrite_Dummy_13,
    SWrite_Dummy_14,
    SWrite_Len_01,
    SWrite_Len_02,
    SWrite_Len_03,
    SWrite_Len_04,
    SWrite_Len_05,
    SWrite_Len_06,
    SWrite_Len_07,
    SWrite_Len_08,
    SWrite_Len_09,
    SWrite_Len_10,
    SWrite_Len_11,
    SWrite_Len_12,
    SWrite_Len_13,
    SWrite_Len_14,
    SWrite_MemAddress_01,
    SWrite_MemAddress_02,
    SWrite_MemAddress_03,
    SWrite_MemAddress_04,
    SWrite_MemAddress_05,
    SWrite_MemAddress_06,
    SWrite_MemAddress_07,
    SWrite_MemAddress_08,
    SWrite_MemAddress_09,
    SWrite_MemAddress_10,
    SWrite_MemAddress_11,
    SWrite_MemAddress_12,
    SWrite_MemAddress_13,
    SWrite_MemAddress_14
} SignalNames;

// LIN-Bus Diagnostic Signals
typedef enum {
    MasterReqB0,
    MasterReqB1,
    MasterReqB2,
    MasterReqB3,
    MasterReqB4,
    MasterReqB5,
    MasterReqB6,
    MasterReqB7,
    SlaveRespB0,
    SlaveRespB1,
    SlaveRespB2,
    SlaveRespB3,
    SlaveRespB4,
    SlaveRespB5,
    SlaveRespB6,
    SlaveRespB7
} DiagnosticSignalNames;

// LIN-Bus Frames
typedef enum {
    RGBe_Slave_d_01_02,
    RGBe_Slave_d_03_04,
    RGBe_Slave_d_05_06,
    RGBe_Slave_d_07_08,
    RGBe_Slave_d_09_10,
    RGBe_Slave_d_11_12,
    RGBe_Slave_d_13_14,
    RGBe_Sync_abcd,
    RGBe_Write_d_01,
    RGBe_Write_d_02,
    RGBe_Write_d_03,
    RGBe_Write_d_04,
    RGBe_Write_d_05,
    RGBe_Write_d_06,
    RGBe_Write_d_07,
    RGBe_Write_d_08,
    RGBe_Write_d_09,
    RGBe_Write_d_10,
    RGBe_Write_d_11,
    RGBe_Write_d_12,
    RGBe_Write_d_13,
    RGBe_Write_d_14,
    RGBs_Slave_01d,
    RGBs_Slave_02d,
    RGBs_Slave_03d,
    RGBs_Slave_04d,
    RGBs_Slave_05d,
    RGBs_Slave_06d,
    RGBs_Slave_07d,
    RGBs_Slave_08d,
    RGBs_Slave_09d,
    RGBs_Slave_10d,
    RGBs_Slave_11d,
    RGBs_Slave_12d,
    RGBs_Slave_13d,
    RGBs_Slave_14d,
    RGBs_Slave_16d
} FrameNames;

// LIN-Bus Diagnostic Frames
typedef enum {
    MasterReq,
    SlaveResp
} DiagnosticFrameNames;

//LIN-Bus Frametypes
typedef enum {
    NormalFrame,
    DiagnosticFrame,
    EndFrame
} FrameTypes;

// LIN-Bus Schedule Tables
typedef enum {
    ST1,
    SWrite,
    Sync_All,
    DiagRequest,
    DiagResponse
} ScheduleNames;

#endif //LDF_TYPEDEFS_H