/*
 * Auto-generated LIN signal header
 * Created by your tool
 */

#ifndef LIN_SIGNALS_H
#define LIN_SIGNALS_H

#include <stdint.h>
#include "ldf_typedefs.h"

typedef struct LinFrame{
    uint8_t u8_idField;
    uint8_t u8_dataptr[8];
    uint8_t u8_checkSum;
    FrameNames fn_frameIndex;
    void(*callback)(struct LinFrame* self);
}LinFrame_t;

typedef struct LinSignalParameter{
    uint16_t data;
    uint8_t length;
    uint8_t offset;
    Nodes publisher;
}LinSignalParameter_t;

typedef struct LinScheduleTable{
    FrameNames frameOrder;
    LinFrame_t linFrame;
    uint16_t delay_ms;
    bool sent;
    bool active;
}LinScheduleTable_t;

typedef struct LinScheduleTableDiag{
    DiagnosticFrameNames frameOrder;
    uint8_t delay_ms;
}LinScheduleTableDiag_t;

#define LIN_BAUDRATE 19200
#define LIN_PROTOCOL_VERSION 2.0
#define LIN_LANGUAGE_VERSION 2.0

extern LinFrame_t RGBe_Slave_d_01_02_t;
void RGBe_Slave_d_01_02_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Slave_d_03_04_t;
void RGBe_Slave_d_03_04_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Slave_d_05_06_t;
void RGBe_Slave_d_05_06_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Slave_d_07_08_t;
void RGBe_Slave_d_07_08_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Slave_d_09_10_t;
void RGBe_Slave_d_09_10_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Slave_d_11_12_t;
void RGBe_Slave_d_11_12_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Slave_d_13_14_t;
void RGBe_Slave_d_13_14_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Sync_abcd_t;
void RGBe_Sync_abcd_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_01_t;
void RGBe_Write_d_01_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_02_t;
void RGBe_Write_d_02_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_03_t;
void RGBe_Write_d_03_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_04_t;
void RGBe_Write_d_04_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_05_t;
void RGBe_Write_d_05_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_06_t;
void RGBe_Write_d_06_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_07_t;
void RGBe_Write_d_07_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_08_t;
void RGBe_Write_d_08_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_09_t;
void RGBe_Write_d_09_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_10_t;
void RGBe_Write_d_10_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_11_t;
void RGBe_Write_d_11_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_12_t;
void RGBe_Write_d_12_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_13_t;
void RGBe_Write_d_13_CB(LinFrame_t* frame);
extern LinFrame_t RGBe_Write_d_14_t;
void RGBe_Write_d_14_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_01d_t;
void RGBs_Slave_01d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_02d_t;
void RGBs_Slave_02d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_03d_t;
void RGBs_Slave_03d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_04d_t;
void RGBs_Slave_04d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_05d_t;
void RGBs_Slave_05d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_06d_t;
void RGBs_Slave_06d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_07d_t;
void RGBs_Slave_07d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_08d_t;
void RGBs_Slave_08d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_09d_t;
void RGBs_Slave_09d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_10d_t;
void RGBs_Slave_10d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_11d_t;
void RGBs_Slave_11d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_12d_t;
void RGBs_Slave_12d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_13d_t;
void RGBs_Slave_13d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_14d_t;
void RGBs_Slave_14d_CB(LinFrame_t* frame);
extern LinFrame_t RGBs_Slave_16d_t;
void RGBs_Slave_16d_CB(LinFrame_t* frame);

typedef struct signals{
    LinSignalParameter_t BCM_RGB_Color_u_01;
    LinSignalParameter_t BCM_RGB_Color_u_02;
    LinSignalParameter_t BCM_RGB_Color_u_03;
    LinSignalParameter_t BCM_RGB_Color_u_04;
    LinSignalParameter_t BCM_RGB_Color_u_05;
    LinSignalParameter_t BCM_RGB_Color_u_06;
    LinSignalParameter_t BCM_RGB_Color_u_07;
    LinSignalParameter_t BCM_RGB_Color_u_08;
    LinSignalParameter_t BCM_RGB_Color_u_09;
    LinSignalParameter_t BCM_RGB_Color_u_10;
    LinSignalParameter_t BCM_RGB_Color_u_11;
    LinSignalParameter_t BCM_RGB_Color_u_12;
    LinSignalParameter_t BCM_RGB_Color_u_13;
    LinSignalParameter_t BCM_RGB_Color_u_14;
    LinSignalParameter_t BCM_RGB_Color_v_01;
    LinSignalParameter_t BCM_RGB_Color_v_02;
    LinSignalParameter_t BCM_RGB_Color_v_03;
    LinSignalParameter_t BCM_RGB_Color_v_04;
    LinSignalParameter_t BCM_RGB_Color_v_05;
    LinSignalParameter_t BCM_RGB_Color_v_06;
    LinSignalParameter_t BCM_RGB_Color_v_07;
    LinSignalParameter_t BCM_RGB_Color_v_08;
    LinSignalParameter_t BCM_RGB_Color_v_09;
    LinSignalParameter_t BCM_RGB_Color_v_10;
    LinSignalParameter_t BCM_RGB_Color_v_11;
    LinSignalParameter_t BCM_RGB_Color_v_12;
    LinSignalParameter_t BCM_RGB_Color_v_13;
    LinSignalParameter_t BCM_RGB_Color_v_14;
    LinSignalParameter_t BCM_RGB_Dimmrampe_01;
    LinSignalParameter_t BCM_RGB_Dimmrampe_02;
    LinSignalParameter_t BCM_RGB_Dimmrampe_03;
    LinSignalParameter_t BCM_RGB_Dimmrampe_04;
    LinSignalParameter_t BCM_RGB_Dimmrampe_05;
    LinSignalParameter_t BCM_RGB_Dimmrampe_06;
    LinSignalParameter_t BCM_RGB_Dimmrampe_07;
    LinSignalParameter_t BCM_RGB_Dimmrampe_08;
    LinSignalParameter_t BCM_RGB_Dimmrampe_09;
    LinSignalParameter_t BCM_RGB_Dimmrampe_10;
    LinSignalParameter_t BCM_RGB_Dimmrampe_11;
    LinSignalParameter_t BCM_RGB_Dimmrampe_12;
    LinSignalParameter_t BCM_RGB_Dimmrampe_13;
    LinSignalParameter_t BCM_RGB_Dimmrampe_14;
    LinSignalParameter_t BCM_RGB_GlobalSync;
    LinSignalParameter_t BCM_RGB_GlobalSync_01;
    LinSignalParameter_t BCM_RGB_GlobalSync_03;
    LinSignalParameter_t BCM_RGB_GlobalSync_05;
    LinSignalParameter_t BCM_RGB_GlobalSync_07;
    LinSignalParameter_t BCM_RGB_GlobalSync_09;
    LinSignalParameter_t BCM_RGB_GlobalSync_11;
    LinSignalParameter_t BCM_RGB_GlobalSync_13;
    LinSignalParameter_t BCM_RGB_Intensitaet_01;
    LinSignalParameter_t BCM_RGB_Intensitaet_02;
    LinSignalParameter_t BCM_RGB_Intensitaet_03;
    LinSignalParameter_t BCM_RGB_Intensitaet_04;
    LinSignalParameter_t BCM_RGB_Intensitaet_05;
    LinSignalParameter_t BCM_RGB_Intensitaet_06;
    LinSignalParameter_t BCM_RGB_Intensitaet_07;
    LinSignalParameter_t BCM_RGB_Intensitaet_08;
    LinSignalParameter_t BCM_RGB_Intensitaet_09;
    LinSignalParameter_t BCM_RGB_Intensitaet_10;
    LinSignalParameter_t BCM_RGB_Intensitaet_11;
    LinSignalParameter_t BCM_RGB_Intensitaet_12;
    LinSignalParameter_t BCM_RGB_Intensitaet_13;
    LinSignalParameter_t BCM_RGB_Intensitaet_14;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_01;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_02;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_03;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_04;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_05;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_06;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_07;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_08;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_09;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_10;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_11;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_12;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_13;
    LinSignalParameter_t BCM_RGB_Sonderfunktion_14;
    LinSignalParameter_t RGB_Slave_01d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_01d_HW_Version;
    LinSignalParameter_t RGB_Slave_01d_IntError;
    LinSignalParameter_t RGB_Slave_01d_ResponseError;
    LinSignalParameter_t RGB_Slave_01d_StoredNAD;
    LinSignalParameter_t RGB_Slave_01d_SW_Version;
    LinSignalParameter_t RGB_Slave_01d_TempState;
    LinSignalParameter_t RGB_Slave_01d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_01d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_02d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_02d_HW_Version;
    LinSignalParameter_t RGB_Slave_02d_IntError;
    LinSignalParameter_t RGB_Slave_02d_ResponseError;
    LinSignalParameter_t RGB_Slave_02d_StoredNAD;
    LinSignalParameter_t RGB_Slave_02d_SW_Version;
    LinSignalParameter_t RGB_Slave_02d_TempState;
    LinSignalParameter_t RGB_Slave_02d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_02d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_03d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_03d_HW_Version;
    LinSignalParameter_t RGB_Slave_03d_IntError;
    LinSignalParameter_t RGB_Slave_03d_ResponseError;
    LinSignalParameter_t RGB_Slave_03d_StoredNAD;
    LinSignalParameter_t RGB_Slave_03d_SW_Version;
    LinSignalParameter_t RGB_Slave_03d_TempState;
    LinSignalParameter_t RGB_Slave_03d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_03d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_04d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_04d_HW_Version;
    LinSignalParameter_t RGB_Slave_04d_IntError;
    LinSignalParameter_t RGB_Slave_04d_ResponseError;
    LinSignalParameter_t RGB_Slave_04d_StoredNAD;
    LinSignalParameter_t RGB_Slave_04d_SW_Version;
    LinSignalParameter_t RGB_Slave_04d_TempState;
    LinSignalParameter_t RGB_Slave_04d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_04d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_05d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_05d_HW_Version;
    LinSignalParameter_t RGB_Slave_05d_IntError;
    LinSignalParameter_t RGB_Slave_05d_ResponseError;
    LinSignalParameter_t RGB_Slave_05d_StoredNAD;
    LinSignalParameter_t RGB_Slave_05d_SW_Version;
    LinSignalParameter_t RGB_Slave_05d_TempState;
    LinSignalParameter_t RGB_Slave_05d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_05d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_06d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_06d_HW_Version;
    LinSignalParameter_t RGB_Slave_06d_IntError;
    LinSignalParameter_t RGB_Slave_06d_ResponseError;
    LinSignalParameter_t RGB_Slave_06d_StoredNAD;
    LinSignalParameter_t RGB_Slave_06d_SW_Version;
    LinSignalParameter_t RGB_Slave_06d_TempState;
    LinSignalParameter_t RGB_Slave_06d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_06d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_07d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_07d_HW_Version;
    LinSignalParameter_t RGB_Slave_07d_IntError;
    LinSignalParameter_t RGB_Slave_07d_ResponseError;
    LinSignalParameter_t RGB_Slave_07d_StoredNAD;
    LinSignalParameter_t RGB_Slave_07d_SW_Version;
    LinSignalParameter_t RGB_Slave_07d_TempState;
    LinSignalParameter_t RGB_Slave_07d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_07d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_08d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_08d_HW_Version;
    LinSignalParameter_t RGB_Slave_08d_IntError;
    LinSignalParameter_t RGB_Slave_08d_ResponseError;
    LinSignalParameter_t RGB_Slave_08d_StoredNAD;
    LinSignalParameter_t RGB_Slave_08d_SW_Version;
    LinSignalParameter_t RGB_Slave_08d_TempState;
    LinSignalParameter_t RGB_Slave_08d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_08d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_09d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_09d_HW_Version;
    LinSignalParameter_t RGB_Slave_09d_IntError;
    LinSignalParameter_t RGB_Slave_09d_ResponseError;
    LinSignalParameter_t RGB_Slave_09d_StoredNAD;
    LinSignalParameter_t RGB_Slave_09d_SW_Version;
    LinSignalParameter_t RGB_Slave_09d_TempState;
    LinSignalParameter_t RGB_Slave_09d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_09d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_10d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_10d_HW_Version;
    LinSignalParameter_t RGB_Slave_10d_IntError;
    LinSignalParameter_t RGB_Slave_10d_ResponseError;
    LinSignalParameter_t RGB_Slave_10d_StoredNAD;
    LinSignalParameter_t RGB_Slave_10d_SW_Version;
    LinSignalParameter_t RGB_Slave_10d_TempState;
    LinSignalParameter_t RGB_Slave_10d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_10d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_11d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_11d_HW_Version;
    LinSignalParameter_t RGB_Slave_11d_IntError;
    LinSignalParameter_t RGB_Slave_11d_ResponseError;
    LinSignalParameter_t RGB_Slave_11d_StoredNAD;
    LinSignalParameter_t RGB_Slave_11d_SW_Version;
    LinSignalParameter_t RGB_Slave_11d_TempState;
    LinSignalParameter_t RGB_Slave_11d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_11d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_12d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_12d_HW_Version;
    LinSignalParameter_t RGB_Slave_12d_IntError;
    LinSignalParameter_t RGB_Slave_12d_ResponseError;
    LinSignalParameter_t RGB_Slave_12d_StoredNAD;
    LinSignalParameter_t RGB_Slave_12d_SW_Version;
    LinSignalParameter_t RGB_Slave_12d_TempState;
    LinSignalParameter_t RGB_Slave_12d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_12d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_13d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_13d_HW_Version;
    LinSignalParameter_t RGB_Slave_13d_IntError;
    LinSignalParameter_t RGB_Slave_13d_ResponseError;
    LinSignalParameter_t RGB_Slave_13d_StoredNAD;
    LinSignalParameter_t RGB_Slave_13d_SW_Version;
    LinSignalParameter_t RGB_Slave_13d_TempState;
    LinSignalParameter_t RGB_Slave_13d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_13d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_14d_HelligkeitsFaktor;
    LinSignalParameter_t RGB_Slave_14d_HW_Version;
    LinSignalParameter_t RGB_Slave_14d_IntError;
    LinSignalParameter_t RGB_Slave_14d_ResponseError;
    LinSignalParameter_t RGB_Slave_14d_StoredNAD;
    LinSignalParameter_t RGB_Slave_14d_SW_Version;
    LinSignalParameter_t RGB_Slave_14d_TempState;
    LinSignalParameter_t RGB_Slave_14d_Weisspunkt_u;
    LinSignalParameter_t RGB_Slave_14d_Weisspunkt_v;
    LinSignalParameter_t RGB_Slave_16d_ResponseError;
    LinSignalParameter_t SWrite_CRC_01;
    LinSignalParameter_t SWrite_CRC_02;
    LinSignalParameter_t SWrite_CRC_03;
    LinSignalParameter_t SWrite_CRC_04;
    LinSignalParameter_t SWrite_CRC_05;
    LinSignalParameter_t SWrite_CRC_06;
    LinSignalParameter_t SWrite_CRC_07;
    LinSignalParameter_t SWrite_CRC_08;
    LinSignalParameter_t SWrite_CRC_09;
    LinSignalParameter_t SWrite_CRC_10;
    LinSignalParameter_t SWrite_CRC_11;
    LinSignalParameter_t SWrite_CRC_12;
    LinSignalParameter_t SWrite_CRC_13;
    LinSignalParameter_t SWrite_CRC_14;
    LinSignalParameter_t SWrite_Data_B1_01;
    LinSignalParameter_t SWrite_Data_B1_02;
    LinSignalParameter_t SWrite_Data_B1_03;
    LinSignalParameter_t SWrite_Data_B1_04;
    LinSignalParameter_t SWrite_Data_B1_05;
    LinSignalParameter_t SWrite_Data_B1_06;
    LinSignalParameter_t SWrite_Data_B1_07;
    LinSignalParameter_t SWrite_Data_B1_08;
    LinSignalParameter_t SWrite_Data_B1_09;
    LinSignalParameter_t SWrite_Data_B1_10;
    LinSignalParameter_t SWrite_Data_B1_11;
    LinSignalParameter_t SWrite_Data_B1_12;
    LinSignalParameter_t SWrite_Data_B1_13;
    LinSignalParameter_t SWrite_Data_B1_14;
    LinSignalParameter_t SWrite_Data_B2_01;
    LinSignalParameter_t SWrite_Data_B2_02;
    LinSignalParameter_t SWrite_Data_B2_03;
    LinSignalParameter_t SWrite_Data_B2_04;
    LinSignalParameter_t SWrite_Data_B2_05;
    LinSignalParameter_t SWrite_Data_B2_06;
    LinSignalParameter_t SWrite_Data_B2_07;
    LinSignalParameter_t SWrite_Data_B2_08;
    LinSignalParameter_t SWrite_Data_B2_09;
    LinSignalParameter_t SWrite_Data_B2_10;
    LinSignalParameter_t SWrite_Data_B2_11;
    LinSignalParameter_t SWrite_Data_B2_12;
    LinSignalParameter_t SWrite_Data_B2_13;
    LinSignalParameter_t SWrite_Data_B2_14;
    LinSignalParameter_t SWrite_Data_B3_01;
    LinSignalParameter_t SWrite_Data_B3_02;
    LinSignalParameter_t SWrite_Data_B3_03;
    LinSignalParameter_t SWrite_Data_B3_04;
    LinSignalParameter_t SWrite_Data_B3_05;
    LinSignalParameter_t SWrite_Data_B3_06;
    LinSignalParameter_t SWrite_Data_B3_07;
    LinSignalParameter_t SWrite_Data_B3_08;
    LinSignalParameter_t SWrite_Data_B3_09;
    LinSignalParameter_t SWrite_Data_B3_10;
    LinSignalParameter_t SWrite_Data_B3_11;
    LinSignalParameter_t SWrite_Data_B3_12;
    LinSignalParameter_t SWrite_Data_B3_13;
    LinSignalParameter_t SWrite_Data_B3_14;
    LinSignalParameter_t SWrite_Data_B4_01;
    LinSignalParameter_t SWrite_Data_B4_02;
    LinSignalParameter_t SWrite_Data_B4_03;
    LinSignalParameter_t SWrite_Data_B4_04;
    LinSignalParameter_t SWrite_Data_B4_05;
    LinSignalParameter_t SWrite_Data_B4_06;
    LinSignalParameter_t SWrite_Data_B4_07;
    LinSignalParameter_t SWrite_Data_B4_08;
    LinSignalParameter_t SWrite_Data_B4_09;
    LinSignalParameter_t SWrite_Data_B4_10;
    LinSignalParameter_t SWrite_Data_B4_11;
    LinSignalParameter_t SWrite_Data_B4_12;
    LinSignalParameter_t SWrite_Data_B4_13;
    LinSignalParameter_t SWrite_Data_B4_14;
    LinSignalParameter_t SWrite_Data_B5_01;
    LinSignalParameter_t SWrite_Data_B5_02;
    LinSignalParameter_t SWrite_Data_B5_03;
    LinSignalParameter_t SWrite_Data_B5_04;
    LinSignalParameter_t SWrite_Data_B5_05;
    LinSignalParameter_t SWrite_Data_B5_06;
    LinSignalParameter_t SWrite_Data_B5_07;
    LinSignalParameter_t SWrite_Data_B5_08;
    LinSignalParameter_t SWrite_Data_B5_09;
    LinSignalParameter_t SWrite_Data_B5_10;
    LinSignalParameter_t SWrite_Data_B5_11;
    LinSignalParameter_t SWrite_Data_B5_12;
    LinSignalParameter_t SWrite_Data_B5_13;
    LinSignalParameter_t SWrite_Data_B5_14;
    LinSignalParameter_t SWrite_Dummy_01;
    LinSignalParameter_t SWrite_Dummy_02;
    LinSignalParameter_t SWrite_Dummy_03;
    LinSignalParameter_t SWrite_Dummy_04;
    LinSignalParameter_t SWrite_Dummy_05;
    LinSignalParameter_t SWrite_Dummy_06;
    LinSignalParameter_t SWrite_Dummy_07;
    LinSignalParameter_t SWrite_Dummy_08;
    LinSignalParameter_t SWrite_Dummy_09;
    LinSignalParameter_t SWrite_Dummy_10;
    LinSignalParameter_t SWrite_Dummy_11;
    LinSignalParameter_t SWrite_Dummy_12;
    LinSignalParameter_t SWrite_Dummy_13;
    LinSignalParameter_t SWrite_Dummy_14;
    LinSignalParameter_t SWrite_Len_01;
    LinSignalParameter_t SWrite_Len_02;
    LinSignalParameter_t SWrite_Len_03;
    LinSignalParameter_t SWrite_Len_04;
    LinSignalParameter_t SWrite_Len_05;
    LinSignalParameter_t SWrite_Len_06;
    LinSignalParameter_t SWrite_Len_07;
    LinSignalParameter_t SWrite_Len_08;
    LinSignalParameter_t SWrite_Len_09;
    LinSignalParameter_t SWrite_Len_10;
    LinSignalParameter_t SWrite_Len_11;
    LinSignalParameter_t SWrite_Len_12;
    LinSignalParameter_t SWrite_Len_13;
    LinSignalParameter_t SWrite_Len_14;
    LinSignalParameter_t SWrite_MemAddress_01;
    LinSignalParameter_t SWrite_MemAddress_02;
    LinSignalParameter_t SWrite_MemAddress_03;
    LinSignalParameter_t SWrite_MemAddress_04;
    LinSignalParameter_t SWrite_MemAddress_05;
    LinSignalParameter_t SWrite_MemAddress_06;
    LinSignalParameter_t SWrite_MemAddress_07;
    LinSignalParameter_t SWrite_MemAddress_08;
    LinSignalParameter_t SWrite_MemAddress_09;
    LinSignalParameter_t SWrite_MemAddress_10;
    LinSignalParameter_t SWrite_MemAddress_11;
    LinSignalParameter_t SWrite_MemAddress_12;
    LinSignalParameter_t SWrite_MemAddress_13;
    LinSignalParameter_t SWrite_MemAddress_14;
} LinSignals_t;

extern LinSignals_t signals;

typedef struct LinDiagnosticSignals{
    uint8_t MasterReqB0;
    uint8_t MasterReqB1;
    uint8_t MasterReqB2;
    uint8_t MasterReqB3;
    uint8_t MasterReqB4;
    uint8_t MasterReqB5;
    uint8_t MasterReqB6;
    uint8_t MasterReqB7;
    uint8_t SlaveRespB0;
    uint8_t SlaveRespB1;
    uint8_t SlaveRespB2;
    uint8_t SlaveRespB3;
    uint8_t SlaveRespB4;
    uint8_t SlaveRespB5;
    uint8_t SlaveRespB6;
    uint8_t SlaveRespB7;
} LinDiagnosticSignals_t;

extern LinDiagnosticSignals_t LinDiagnosticSignal;

extern LinScheduleTable ST1_table[120];
extern LinScheduleTable SWrite_table[14];
extern LinScheduleTable Sync_All_table[1];
extern LinScheduleTableDiag DiagRequest_table[1];
extern LinScheduleTableDiag DiagResponse_table[1];
#endif // LIN_SIGNALS_H
